#Volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.environment.storage }}
---
#Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tourmysql
spec:
  selector:
    matchLabels:
      app: tourmysql
  template:
    metadata:
      labels:
        app: tourmysql
    spec:
      containers:
        - name: tourmysql
          image: {{ .Values.tourapp.tourmysqlimage }}:{{ .Values.tourapp.tourmysqltag }}
          imagePullPolicy: {{ .Values.tourapp.tourmysqlpullPolicy }}
          ports:
            - containerPort: {{ .Values.service.tourmysqlinternalPort }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.environment.MYSQL_ROOT_PASSWORD }}
            - name: MYSQL_DATABASE
              value: {{ .Values.environment.MYSQL_DATABASE }}
            - name: MYSQL_USER
              value: {{ .Values.environment.MYSQL_USER }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.environment.MYSQL_PASSWORD }}
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mysqldb
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: tourmysql
spec:
  selector:
    app: tourmysql
  ports:
    - port: {{ .Values.service.tourmysqlexternalPort }}
      protocol: TCP
      targetPort: {{ .Values.service.tourmysqlinternalPort }}